### PR TITLE
replace link to defunct jamonapi.com

### PR DESCRIPTION
**Pull request by carehart**
content at jamonapi.com is no longer related to this project, it seems

### CODE REVIEW

**Comment by carehart** [comment]
While I'd hope you'd agree this is an appropriate change to make, if you prefer to link to some other resource, feel free of course. 

It's just that I see that the old domain may have been given up some years ago, as I see the current site's seemingly unrelated content has been like that for a few years, according to tracking of the content at web.archive.org. And since I see there that in 2015 it was told to redirect instead to the sourceforge page, I figured that may be the right choice here.

I do realize it's possible even THAT page is no longer being kept up to date, but it seemed better to propose some change rather than leave the old link, going where it did. :-) 

Finally, FWIW, that soureforge page has a itself two references to jamonapi.com, one being an email address (which I would assume doesn't work any more, but again Steve you will know best).

And thanks for all your years of effort with the tool (and your updating things here even in 2021!)

**Comment by stevensouza** [comment]
Thanks for catching that.  I used to pay for www.jamonapi.com and you are right I no longer pay for it.  I do still work on the project time permitting.  Thanks again for your help.

**Comment by carehart** [comment]
Glad to have helped. Related to this, I see that the repo title/description says, "Another repo for jamonapi.com which is primarily hosted on source forge". I can't propose that change as a pr. (Also, as for the wording there might the roles be reversed, with sf being secondary to the github repo, as for code at least? Or are they mirrored? I realize you've left sf as the primary docs.)

Finally, there are lots of remaining code references to the old url and email address. I could offer a pr for them if you'd like, but what email address should be used instead of the javamonapi.com one, if any?

**Comment by stevensouza** [comment]
<<Related to this, I see that the repo title/description says, "Another repo for jamonapi.com which is primarily hosted on source forge". I can't propose that change as a pr. (Also, as for the wording there might the roles be reversed, with sf being secondary to the github repo, as for code at least? Or are they mirrored? I realize you've left sf as the primary docs.)>>
The wording is probably a bit old.  The project was originally hosted on sourceforge, but now it is mirrored on both sites, so neither is really primary.  They are both in sync.  Yes, the documentation is kept on sourceforge though.

<<Finally, there are lots of remaining code references to the old url and email address. I could offer a pr for them if you'd like, but what email address should be used instead of the javamonapi.com one, if any?>>
Sure, sounds good,  As far as email you could use steve at stevesouza.com


Finally, there are lots of remaining code references to the old url and email address. I could offer a pr for them if you'd like, but what email address should be used instead of the javamonapi.com one, if any?

**Comment by stevensouza** [comment]
Do you use jamon?

**Pull request merged**
